service: pdf-generator

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2
  stage: ${opt:stage, 'dev'}
  memorySize: 1024
  timeout: 30
  environment:
    STAGE: ${self:provider.stage}
  apiGateway:
    binaryMediaTypes:
      - "*/*"
  layers:
    - arn:aws:lambda:eu-west-2:764866452798:layer:chrome-aws-lambda:8

functions:
  convert:
    handler: handler.convert
    role: arn:aws:iam::775052747630:role/LBH_Lambda_Execution
    events:
      - http:
          path: /
          method: post
