version: 2.1

executors:
  my-executor:
    docker:
      - image: circleci/node:12.13

    working_directory: ~/repo

jobs:
  build:
    executor: my-executor

    steps:
      - checkout

      - setup_remote_docker

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            sudo npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Run linter
          command: npm run lint

      # - run:
      #     name: Run tests
      #     command: make build test-ci

      - run:
          name: Build layers
          command: make perl-layer image-layer

      - run:
          name: Install Serverless CLI
          command: |
            sudo npm i -g serverless

      - run:
          name: Set AWS credentials
          command: |
            pushd ~ && serverless config credentials -p aws -k ${AWS_ACCESS_KEY_ID} -s ${AWS_SECRET_ACCESS_KEY} -n hackney && popd

      - run:
          name: Deploy application
          command: sls deploy -s test --aws-profile hackney

      - run:
          name: Test application
          command: TEST_URL=${TEST_ENDPOINT_TEST} make test-ci
          
      - persist_to_workspace:
          root: ~/repo
          paths: .

  deploy-staging:
    executor: my-executor

    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Install Serverless CLI
          command: |
            sudo npm i -g serverless

      - run:
          name: Set AWS credentials
          command: |
            pushd ~ && serverless config credentials -p aws -k ${AWS_ACCESS_KEY_ID} -s ${AWS_SECRET_ACCESS_KEY} -n hackney && popd

      - run:
          name: Deploy application
          command: sls deploy -s staging --aws-profile hackney

      - run:
          name: Test application
          command: TEST_URL=${TEST_ENDPOINT_STAGING} make test-ci

  deploy-production:
    executor: my-executor

    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Install Serverless CLI
          command: |
            sudo npm i -g serverless

      - run:
          name: Set AWS credentials
          command: |
            pushd ~ && serverless config credentials -p aws -k ${AWS_ACCESS_KEY_ID} -s ${AWS_SECRET_ACCESS_KEY} -n hackney && popd

      - run:
          name: Deploy application
          command: sls deploy -s production --aws-profile hackney

      - run:
          name: Test application
          command: TEST_URL=${TEST_ENDPOINT_PROD} make test-ci

workflows:
  version: 2
  continuous-delivery:
    jobs:
      - build
      - deploy-staging:
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - permit-deploy-production:
          type: approval
          requires:
            - deploy-staging
      - deploy-production:
          requires:
            - permit-deploy-production
